services:
  postgres:
    image: postgres:16-alpine
    container_name: bot_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=botdb
    ports:
      - "5432:5432"
